---
- hosts: local

  tasks:

    - name: Check that the server's alive
      action: ping

    - name: check nginx
      service: name=nginx state=started

    - name: check nginx
      command: service nginx status
      register: nginx_status

    - debug: msg="{{ nginx_status.stdout }}"

